# Выкладывает самую свежую версию карты Джомтьена на GitHub Pages.
# Ищет новейший файл Pattaya_Jomtien_*.html в папке Codex, копирует его
# в index.html, коммитит и отправляет на GitHub. Без изменений — ничего не делает.
$ErrorActionPreference = 'Stop'
$repo = $PSScriptRoot
$codex = Join-Path $env:USERPROFILE 'Documents\Codex'

$latest = Get-ChildItem -Path $codex -Recurse -Filter 'Pattaya_Jomtien_*.html' |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1
if (-not $latest) { throw "В $codex не найден ни один файл Pattaya_Jomtien_*.html" }

Write-Host "Свежий файл: $($latest.FullName) ($($latest.LastWriteTime))"
Copy-Item $latest.FullName (Join-Path $repo 'index.html') -Force

# Add the link to the support-schedule page (support/index.html) into the map's nav.
# The map is regenerated by Codex from scratch, so the link must be re-inserted on every publish.
$indexPath = Join-Path $repo 'index.html'
$html = Get-Content $indexPath -Raw -Encoding UTF8
$link = '<a href="support/" class="ext-support">' + [char]0x0413 + [char]0x0440 + [char]0x0430 + [char]0x0444 + [char]0x0438 + [char]0x043A + ' ' + [char]0x0441 + [char]0x0430 + [char]0x043F + [char]0x043F + [char]0x043E + [char]0x0440 + [char]0x0442 + [char]0x0430 + ' ' + [char]0x043C + [char]0x0430 + [char]0x0441 + [char]0x0442 + [char]0x0435 + [char]0x0440 + [char]0x043E + [char]0x0432 + ' ' + [char]0x2192 + '</a>'
if ($html -notmatch 'href="support/"' -and $html -match '</nav>') {
    $html = [regex]::new('</nav>').Replace($html, $link + '</nav>', 1)
    [IO.File]::WriteAllText($indexPath, $html, (New-Object Text.UTF8Encoding $false))
}

$readme = Join-Path $repo 'README.md'
(Get-Content $readme -Raw) -replace 'Опубликованная версия: .*', "Опубликованная версия: $($latest.Name)" |
    Set-Content $readme -NoNewline

Set-Location $repo
if (-not (git status --porcelain)) { Write-Host 'Изменений нет — на сайте уже эта версия.'; exit 0 }
git add index.html README.md
git commit -q -m "map: publish $($latest.Name)"
git push -q origin main
Write-Host 'Готово. Страница обновится через 1–2 минуты:'
Write-Host 'https://martini2023rus-crypto.github.io/pattaya-jomtien-map/'
